services:
  # A Web Service for the Backend
  - type: web
    name: Yardstick-Assignment backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: MONGO_URI
        sync: false # You will add this secret in the dashboard
      - key: JWT_SECRET
        sync: false # You will add this secret in the dashboard

  # A Static Site for the Frontend
  - type: static
    name: Yardstick-Assignment frontend
    env: static
    rootDir: frontend
    buildCommand: "npm run build"
    publishDir: "build"
    # This is the rewrite rule that was missing from the UI!
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: Yardstick-Assignment backend
          property: url # This automatically gets the backend's live URL
