services:
  # Service 1: The Backend API
  - type: web
    name: Yardstick-Assignment backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: MONGO_URI
        sync: false # Set this secret value in the Render Dashboard
      - key: JWT_SECRET
        sync: false # Set this secret value in the Render Dashboard

  # Service 2: The Frontend Static Site
  - type: static_site
    name: Yardstick-Assignment frontend
    plan: free
    rootDir: frontend
    buildCommand: "npm run build"
    publishDir: "build"
    # The rewrite rule for React Router
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: Yardstick-Assignment backend
          property: url # Automatically gets the backend's URL and adds '/api'
          path: /api
