services:
  # 1. Backend Web Service (No changes here)
  - type: web
    name: Yardstick-Assignment backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # 2. Frontend as a Static Web Service
  - type: web # We use the 'web' type for the frontend now
    name: Yardstick-Assignment frontend
    env: static # This specifies it's a STATIC site
    rootDir: frontend
    plan: free
    buildCommand: "npm run build"
    # This tells Render where your built static files are
    staticPublishPath: build
    # No start command is needed for a static site
    # The rewrite rule will be handled at the top level
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: Yardstick-Assignment backend
          property: url

# 3. Top-level Rewrite Rule for the Frontend
rewrites:
  - source: /api/*
    # This rewrite is a placeholder, as the backend service will handle these paths
    # It ensures these paths are not caught by the frontend rewrite
    destination: /api/* - source: /*
    destination: /index.html
    service: 
      name: Yardstick-Assignment frontend
      type: web
